---
- name: Install EarlyOOM
  tags: [earlyoom, earlyoom_install]
  package:
    name: "{{ __earlyoom_dependencies }}"
    state: present

- name: Configure EarlyOOM
  tags: [earlyoom, earlyoom_config]
  template:
    src: earlyoom.j2
    dest: "{{ __earlyoom_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart earlyoom
  vars:
    cfg: "{{ __earlyoom_config_defaults | combine(earlyoom_config) }}"

- name: Manage EarlyOOM service
  tags: [earlyoom, earlyoom_service]
  service:
    name: "{{ __earlyoom_service_name }}"
    state: "{{ earlyoom_service_state }}"
    enabled: "{{ earlyoom_service_enabled }}"
